services:
  nginx:
    image: nginx:1.27-alpine
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./DockerScripts/Nginx/conf.d/django.conf:/etc/nginx/conf.d/django.conf:ro
      - ./DockerScripts/Nginx/conf.d/fs-admin.conf:/etc/nginx/conf.d/fs-admin.conf:ro
      - ./DockerScripts/Nginx/conf.d/fs-s3.conf:/etc/nginx/conf.d/fs-s3.conf:ro
      - ./DockerScripts/Nginx/conf.d/adminer.conf:/etc/nginx/conf.d/adminer.conf:ro
      - ./ssl:/etc/nginx/certs:ro
    networks:
      public-network:
        ipv4_address: 172.20.0.12
    depends_on:
      - django
      - fs-admin
      - adminer
  django:
    build:
      context: ./src
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./src:/app
    networks:
      public-network:
        ipv4_address: 172.20.0.11
    depends_on:
      - db
      - redis
      - fs-s3
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: earpiece
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password4231
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      public-network:
        ipv4_address: 172.20.0.22
  adminer:
    image: adminer:latest
    restart: unless-stopped
    networks:
      public-network:
        ipv4_address: 172.20.0.14
    depends_on:
      - db
  redis:
    image: redis:7-alpine
    restart: always
    networks:
      public-network:
        ipv4_address: 172.20.0.21
  fs-master:
    image: chrislusf/seaweedfs:latest
    restart: unless-stopped
    volumes:
      - ./volumes/fs_master:/data
    command: master -ip.bind=0.0.0.0 -mdir=/data
    networks:
      public-network:
        ipv4_address: 172.20.0.61
  fs-admin:
    image: chrislusf/seaweedfs:latest
    restart: unless-stopped
    command: admin -port 80 -masters="fs-master:9333" -dataDir=/data
    volumes:
      - ./volumes/fs_admin:/data
    networks:
      public-network:
        ipv4_address: 172.20.0.66
  fs-volume:
    image: chrislusf/seaweedfs:latest
    restart: unless-stopped
    volumes:
      - ./volumes/fs_volume:/data
    command: volume -master=fs-master:9333 -port=443 -dir=/data
    depends_on:
      - fs-master
    networks:
      public-network:
        ipv4_address: 172.20.0.62
  fs-filer:
    image: chrislusf/seaweedfs:latest
    restart: unless-stopped
    command: filer -master=fs-master:9333 -ip.bind=0.0.0.0
    depends_on:
      - fs-master
      - fs-volume
    networks:
      public-network:
        ipv4_address: 172.20.0.63
  fs-s3:
    image: chrislusf/seaweedfs:latest
    restart: unless-stopped
    environment:
      - AWS_ACCESS_KEY_ID=myaccesskeyid
      - AWS_SECRET_ACCESS_KEY=mysecretaccesskey
    command: s3 -filer=fs-filer:8888 -ip.bind=0.0.0.0
    depends_on:
      - fs-filer
    networks:
      public-network:
        ipv4_address: 172.20.0.64
volumes:
  db:
networks:
  public-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
