server {
    listen $FS_ADMIN_PORT$ ssl;
    server_name $FS_ADMIN_DOMAIN$;

    ssl_certificate    $SSL_CERTIFICATE_PUBLIC_KEY_PATH$; 
    ssl_certificate_key $SSL_CERTIFICATE_PRIVATE_KEY_PATH$;

    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    location / {
        proxy_pass         http://fs-admin/;
        proxy_http_version 1.1;
        
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection keep-alive;
        
        proxy_set_header   Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   X-Forwarded-Ssl on;
    }
}
