# Generated by Django 5.0.14 on 2026-07-07 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='filemetadata',
            name='file_type',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='filemetadata',
            name='fs_id',
            field=models.UUIDField(null=True),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('cover', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.filemetadata')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('is_public', models.BooleanField(default=True)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.album')),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.artist')),
                ('music_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.filemetadata')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=70)),
                ('is_public', models.BooleanField(default=False)),
                ('cover', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.filemetadata')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('songs', models.ManyToManyField(blank=True, related_name='playlists', to='api.music')),
            ],
        ),
    ]
