# Generated by Django 5.0.14 on 2026-07-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_artist_cover_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='length',
            field=models.IntegerField(default=0),
        ),
    ]
